'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reservation
    
    '''<summary>
    '''webForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents webForm As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents [date] As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''calendarButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''calendarHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarHiddenField As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''reservedTimesArrayField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reservedTimesArrayField As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reserveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reserveButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''weekDayInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents weekDayInput As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''weekNumberInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents weekNumberInput As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''isFormFilled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents isFormFilled As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''selectedTimes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedTimes As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
